package br.com.impacta.javaweb.despesas.model;

public enum CategoriaDespesa {
	ALIMENTACAO, CUIDADOS_PESSOAIS, DIVERSOS, DOACOES, EDUCACAO, LAZER, MORADIA, SAUDE, 
	SUPERMECADO, TRANSPORTE, VEICULO, VESTUARIO, VIAGEM;
	
}
